language: python
python:
  - "2.7"
  - "3.6"      # current default Python on Travis CI
  - "nightly"  # nightly build

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - pytest  02_unittest_vs_pytest/*.py

after_success: |
  if [ -n "$GITREPO_TOKEN" -a "x$TRAVIS_BRANCH" = "xmaster" ]; then
    git clone https://innopearl:${GITREPO_TOKEN}@github.com/innopearl/autogen.git &>/dev/null
    cd autogen
    date +%Y-%m-%d-%H:%M:%S > geninfo.txt
    git add geninfo.txt
    git -c user.name='innopearl' -c user.email='innopearl@users.noreply.github.com' commit -m autocommit
    # Make sure to make the output quiet, or else the API token will leak!
    git push -f -q https://innopearl:${GITREPO_TOKEN}@github.com/innopearl/autogen.git &>/dev/null
  fi    
